#!/usr/bin/env php
<?php

declare(strict_types=1);

$dir = __DIR__;

while (true) {
    $candidate = $dir . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

    if (is_file($candidate)) {
        require $candidate;
        break;
    }

    $parent = dirname($dir);

    if ($parent === $dir) {
        throw new RuntimeException('Unable to locate Composer autoload.php');
    }

    $dir = $parent;
}

use Symfony\Component\Console\Application;
use TeamRadHQ\ConfigTemplates\Console\InstallTemplate;
use TeamRadHQ\ConfigTemplates\Console\ListTemplates;

$application = new Application;
$application->addCommand(new ListTemplates);
$application->addCommand(new InstallTemplate);

try {
    $application->run();
} catch (Exception $exception) {
    echo $exception->getMessage();

    if (getenv('APP_DEBUG') !== false) {
        var_dump($exception);
    }

    exit(1);
}
