name: Update Packagist

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist Update
        run: |
          curl -XPOST -H'Content-Type:application/json' "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" -d '{"repository":{"url":"https://github.com/teamradhq/config-templates"}}'
